# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55897f34717c9c0465d982550a6da28a966e3949fd13a9ce61a5b053bc4fd4cfb133fa33414e513dcba47bb7eb4b5f6e9e23de93086eb12a7e574f4cac9109c4

test:
  secret_key_base: 9cf347694c33832c251c6846b33c207e9dd0364f6dceb25a09d9980bdd11cc6f72915d894233ddbc710c916d623aca81a50579b16a78e25e2dc8c300076dbec1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
